add grid proxy health check
threefoldtecharchive/tfgrid_monitoring_bot pull request #28
Opened 2023-02-28 12:15 UTC by AbdelrahmanElawady

### Description

Remove node checks and add grid proxy health check

### Related Issues

#27 

### Checklist

- [x] Tests included
- [x] Build pass
- [x] Documentation
- [x] Code format and docstrings

2023-02-28 14:17 UTC, xmonader approved these changes

2023-03-05 13:50 UTC, rawdaGastan requested changes

2023-03-05 13:50 UTC, rawdaGastan commented on internal/monitor.go
> +		err := m.monitorNewtorks()
monitorNetworks

2023-03-05 13:50 UTC, rawdaGastan commented on internal/monitor.go
> +		err := m.monitorNewtorks()
You can install `code spell checker` extension :D

2023-03-05 13:58 UTC, merged